### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by timksf** [kazkojima/colorlight-i5-tips#2]
Hello,

I don't know if this is the right place but I have some questions regarding the process of getting linux-on-litexvexriscv to work with the colorlight i5.
What I want to do is boot linux from a remote TFTP server and NFS filesystem via ethernet. I'll just list the questions that came up:
1. How did you generate the defconfig for the colorlight board? 
2. To compille the linux kernel did you just follow the steps in the linux-on-litex-vexriscv repo and use your custom defconfig? Or are there some other steps to take?
3. How exactly do you apply this patch (before or after compiling the kernel? I couldn't find a linux directory in my linux-on-litex-vexriscv/buildroot/patches path) : 
```
$ for f in YOUR_linux-on-litex-vexriscv_PATH/buildroot/patches/linux/000[124]*.patch; do (cat $f | patch -p1); done
```
Thanks in advance for any help.

**Comment by kazkojima** [comment]
Hi,

I'm afraid my response won't be of much help.

1. I've generated it by hand, i.e. with menuconfig.
2. The former.
3. Before compiling kernel.

The linux-on-litex-vexriscv and buildroot/kernel/toolchains have changed and improved a lot since this article was written.
Unfortunately, the things here are already quite old and should not be compatible with the current linux-on-litex-vexriscv. Many issues which the patches tried to fix were solved on the newer version.
I guess that the only thing here that would be still helpful is [how to change the opensbi configuration](https://github.com/kazkojima/colorlight-i5-tips/blob/main/linux/opensbi-config-fixmap.patch).

**Comment by timksf** [comment]
Hi, 
thanks for your quick answer, I just checked out how the repo looked 10 months ago, you're right, a lot has changed since then. 
I think I'll just use one of the supported boards when I want to try linux-on-litex.
My main goal was to validate the ethernet board I built for the colorlight i5, which I'll probably do with a simpler setup now.
